### PR TITLE
[Test Case]: Alignment Curves

### LINKED ISSUE #4: [Test Case]: Alignment Curves
### **Test Case Purpose**
*Please provide a brief description of the purpose of the Test case proposal*

Test case covering the export of simple generic alignment definitions covering common alignment segment types required by all domains.

### **Scope Summary**
*please provide some information around the scope of your test case proposal*

Alignment Curve definition mounted to minimal spatial structure with geospatial positioning. Curve segment definitions covering:

- Horizontal
  - Line (linear)
  - Circular Arc
  - Clothoid
- Vertical
  - Line (linear)
  - Circular Arc 

### **Test Case Proposal**

**MVD Code**: IFC4x3_AbRV  
**Exchange Code**: E1     
**Name**: Alignment Curves   
**Test Code**: ALIG       

### **Additional context**
*Add any other context about the test case proposal here.*

[Miro Dependence Card](https://miro.com/app/board/o9J_lkyDq70=/?moveToWidget=3458764515141203437&cot=14)

### PR DESCRIPTION
**Pull request by SergejMuhic**
## Summary

*Outline of the content and tasks addressed by this pull request, dont forget to link the relevent issue(s)*

Resolves #4 

Adding test instruction first stage documentation for `[Test Case]: Alignment Curves `

Tagging @JuhaHy

## Purpose
Please mark the relevent tasks that this pull request creates or updates:

### Test Cases

- [x] Creation of new test case
- [x] Test case summary
- [ ] Itemised roots & test case imports
- [ ] Usages, constraints & logic
- [ ] Validation criteria & Results
- [ ] Dataset Content & Documentation

### CODE REVIEW

**Comment by AlexBrad1eyCT** [comment]
@SergejMuhic, few things initially:

1. You missed the test case folder, path to the md file should be /E1-ALRF/ALIGN/Readme.md, see the folder template XXXX in docs, the readme links should work if you use the suggested coding.
2. Can you update to the new template also it has a few extra bits for identification and doc control
3. It should be a test case per pull request, not exchange per PR can you split linear placement in to a separate one as I feel when we get to the files there is going to be quite alot of discusssion

PS well done on being first! 😄

**Comment by SergejMuhic** [comment]
> @SergejMuhic, few things initially:
> 
>     1. You missed the test case folder, path to the md file should be /E1-ALRF/ALIGN/Readme.md, see the folder template XXXX in docs, the readme links should work if you use the suggested coding.
> 
>     2. Can you update to the new template also it has a few extra bits for identification and doc control
> 
>     3. It should be a test case per pull request, not exchange per PR can you split linear placement in to a separate one as I feel when we get to the files there is going to be quite alot of discusssion
> 
> 
> PS well done on being first! 😄

Addressed the points. Think I got it now. One question though on the every test instruction having its own PR. Branching of that should then be done on my fork, are we sure that everyone understands that?

**Comment by AlexBrad1eyCT** [comment]
i does say that in [the Contributing guidelines](https://github.com/bSI-InfraRoom/MVD-Infra-Test-Instructions/blob/develop/docs/CONTRIBUTING.md#forking--branches), i will mention it tomorrow, I always use branches on my fork because i am usually addressing more than one item at a time and try to seperate my changes.

**Comment by SergejMuhic** [comment]
Closing this PR to account for branching.

**Pull request closed without merging**
